In [1]:
import pandas as pd
import numpy as np

## [1] 데이터 준비
- DF 로딩 / 기본 정보 확인

In [2]:
file1 = '서울SK.xlsx'
df1 = pd.read_excel(file1)

file2 = '대구한국가스공사.xlsx'
df2 = pd.read_excel(file2)

file3 = '수원KT.xlsx'
df3 = pd.read_excel(file3)

file4 = '서울삼성.xlsx'
df4 = pd.read_excel(file4)

file5 = '고양캐롯.xlsx'
df5 = pd.read_excel(file5)

In [10]:
# 데이터프레임 연결
df = pd.concat([df1, df2, df3, df4, df5], axis = 0)
df.drop([0], inplace=True)
df.drop(['순위'],axis = 1 , inplace=True)
df.reset_index()
df

선수명      팀   PTS    FG   FGA   FG%   FT  FTA    FT%   PP   PPA    PP%  \
1   자밀 워니  서울 SK  24.2  10.4  20.2  51.5  3.0  4.6   66.4  9.4  16.6   56.5   
2     김선형  서울 SK  16.3   6.1  12.6  48.3  2.9  3.9   73.9  4.4   7.8   56.8   
3     최준용  서울 SK  12.7   4.5  11.2  40.5  2.2  3.8   58.2  2.5   4.4   57.0   
4     허일영  서울 SK   9.4   3.2   7.0  46.2  1.7  2.1   81.0  1.3   2.2   60.5   
5     최부경  서울 SK   7.2   3.0   5.4  55.6  1.2  1.7   73.5  2.5   3.4   73.3   
..    ...    ...   ...   ...   ...   ...  ...  ...    ...  ...   ...    ...   
16    박진철  고양 캐롯   1.8   0.8   1.2  62.9  0.2  0.4   58.3  0.7   1.0   69.0   
17    조재우  고양 캐롯   1.7   0.7   1.3  50.0  0.3  0.7   50.0  0.0   0.7    0.0   
18    임종일  고양 캐롯   0.7   0.3   1.1  27.3  0.1  0.1  100.0  0.3   0.6   50.0   
19    이정제  고양 캐롯   0.7   0.3   0.7  50.0  0.0  0.0    0.0  0.3   0.3  100.0   
20    정해원  고양 캐롯   0.3   0.1   0.9  12.5  0.1  0.2   50.0  0.0   0.0    0.0   

    OFF  DEF   TOT  AST   TO  STL   BS   PF  
1   3.1  8.1  11.2  3.1  1.8  1.3  0.9  1.6  
2   0.5  2.1   2.7  6.8  2.3  1.4  0.4  1.8  
3   1.0  4.9   5.9  3.8  1.8  0.8  0.7  2.7  
4   1.2  2.8   4.0  0.6  0.4  0.7  0.1  2.2  
5   2.0  3.0   5.0  1.0  0.6  0.9  0.3  2.2  
..  ...  ...   ...  ...  ...  ...  ...  ...  
16  0.8  1.3   2.0  0.3  0.4  0.2  0.1  1.8  
17  0.3  0.7   1.0  0.0  0.3  0.0  0.3  1.0  
18  0.4  0.7   1.1  0.4  0.1  0.0  0.0  0.5  
19  0.0  0.3   0.3  0.0  0.0  0.3  0.0  0.7  
20  0.1  0.2   0.3  NaN  NaN  NaN  NaN  NaN  

[101 rows x 20 columns]

In [11]:
# 기본 정보 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 101 entries, 1 to 20
Data columns (total 20 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   선수명     101 non-null    object 
 1   팀       101 non-null    object 
 2   PTS     101 non-null    float64
 3   FG      101 non-null    float64
 4   FGA     101 non-null    float64
 5   FG%     101 non-null    float64
 6   FT      101 non-null    float64
 7   FTA     101 non-null    float64
 8   FT%     101 non-null    float64
 9   PP      101 non-null    float64
 10  PPA     101 non-null    float64
 11  PP%     101 non-null    float64
 12  OFF     101 non-null    float64
 13  DEF     101 non-null    float64
 14  TOT     100 non-null    float64
 15  AST     97 non-null     float64
 16  TO      96 non-null     float64
 17  STL     96 non-null     float64
 18  BS      96 non-null     float64
 19  PF      96 non-null     float64
dtypes: float64(18), object(2)
memory usage: 16.6+ KB


### 각 열의 고유값 확인

In [18]:
df.AST.unique()

array([3.1, 6.8, 3.8, 0.6, 1. , 1.9, 1.5, 0.4, 0.1, 0.5, 1.1, 0.3, 0.8,
       0. , 4.1, 1.6, 2.5, 2.1, 2. , 3.7, 1.2, 1.4, 2.6, 2.8, 0.7, 1.7,
       0.2, 3.9, 0.9, 2.7, 3.2, 3.3, 4.2])

In [14]:
df.TO.unique()

array([1.8, 2.3, 0.4, 0.6, 0.7, 0.2, 0.3, 0.5, 0. , 2.5, 1.1, 2. , 1.7,
       1.4, 0.9, 1. , 0.8, 1.5, 0.1, 2.6, 1.6, 2.2, 1.2, 2.1, 1.3])

In [15]:
df.STL.unique()

array([1.3, 1.4, 0.8, 0.7, 0.9, 0.4, 0.3, 0.2, 0.6, 0. , 1.2, 0.5, 1.1,
       1. , 0.1, 1.7])

In [16]:
df.BS.unique()

array([0.9, 0.4, 0.7, 0.1, 0.3, 0. , 0.2, 0.8, 0.6, 0.5, 1.1])

In [17]:
df.PF.unique()

array([1.6, 1.8, 2.7, 2.2, 2.6, 2.5, 1.4, 1. , 1.7, 1.3, 1.9, 0.5, 0.9,
       0.8, 0. , 2.1, 2. , 2.4, 3. , 1.2, 2.3, 0.7, 2.9, 1.5, 3.3])

### NaN 값 처리

In [19]:
# NaN값을 0으로 처리
df.replace(np.NaN, 0, inplace=True)
df.isna().sum()

선수명    0
팀      0
PTS    0
FG     0
FGA    0
FG%    0
FT     0
FTA    0
FT%    0
PP     0
PPA    0
PP%    0
OFF    0
DEF    0
TOT    0
AST    0
TO     0
STL    0
BS     0
PF     0
dtype: int64